apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
images:
  - name: humorvibes-research
    newName: ghcr.io/aidonerightcorp/humorvibes-jestry
    digest: sha256:95568eb899c1a3aa51d8dc1a0884212390f9cc4e85c3aa643477a6355673f4e7
