apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
images:
  - name: humorvibes-research
    newName: ghcr.io/aidonerightcorp/humorvibes-jestry
    digest: sha256:b08c221c8f47056875508088d994eff673fc1357bf9b3d4d9f5ed27efe0a02a0
