apiVersion: v2
name: humorvibes
description: Deploy the HumorVibes research and application API
type: application
version: 0.4.0
appVersion: "0.4.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/aidonerightcorp/humorvibes-jestry
sources:
  - https://github.com/aidonerightcorp/humorvibes-jestry
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: added
      description: Initial chart for the SDK/API application layer.
