apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: humorvibes-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: humorvibes
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress: []
